apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: opc-ecosystem-images
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-nshift-pipelines-tenant/ecosystem-images/opc-ecosystem-images@sha256:e247c9086a9d89b888a636fe56ec103dd6bc60dd9165bfc04aedadfd4946903d
        name: container-image
        resources: {}
status: {}
