apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: opc-ecosystem-images
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opc-ecosystem-images
    app.kubernetes.io/part-of: ecosystem-images
  name: opc-ecosystem-images
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: opc-ecosystem-images
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: opc-ecosystem-images
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-nshift-pipelines-tenant/ecosystem-images/opc-ecosystem-images@sha256:e247c9086a9d89b888a636fe56ec103dd6bc60dd9165bfc04aedadfd4946903d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
